name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the version of Node.js required for your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload source maps to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npx sentry-cli releases new -p javascript-nextjs $GITHUB_SHA
          npx sentry-cli releases set-commits --auto $GITHUB_SHA
          npx sentry-cli releases files $GITHUB_SHA upload-sourcemaps ./build
          npx sentry-cli releases finalize $GITHUB_SHA
