import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fireplace Palace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/fire-icon.png" />
      <body className="${inter.className} flex flex-row">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
